name: OPENSHIFT-_TEST
runtime: node
invoke: http
triggers:
  - name: http
    type: http
    source: / # Specifies the HTTP trigger (you can modify the path)
    auth: none

# Environment variables can be defined here
envs:
  - name: NODE_ENV
    value: production

# Resources such as memory and CPU limits
resources:
  limits:
    memory: 256Mi
    cpu: 500m
  requests:
    memory: 128Mi
    cpu: 200m

# Optional: Health checks
healthEndpoints:
  liveness: /health
  readiness: /readiness
